import type { NextPage } from "next";
import Head from "next/head";
import { Box, Stack, Button, TextField } from "@mui/material";
import {
  signIn,
  signOutUser,
  ProfilePic,
  UserName,
  setMsg,
  Msg,
  useMsgs,
  setImgMsg,
} from "../components/ChatFirebase";
import Grid from "@mui/material/Grid";
import { Input } from "@mui/material";
import React, { useState, useEffect, useRef } from "react";
import { Global, css } from "@emotion/react";
import { atom, useRecoilValue, useSetRecoilState } from "recoil";
import { cssBackgroundState } from "../recoil/cssMsgStates";
import { CustomDrawer } from "../components/GlobalUi";

const Home: NextPage = () => {
  const [text, setText] = useState("コメント");
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setText(event.target.value);
  };

  const cssText = useRecoilValue(cssBackgroundState);
  return (
    <div>
      <Global
        styles={css`
          body {
            ${cssText}
          }
        `}
      />
      <Head>
        <title>Hamu House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomDrawer>
        <Grid
          container
          spacing={0}
          direction="column"
          alignItems="center"
          justifyContent="center"
          style={{ minHeight: "100vh" }}
        >
          <Box>
            <Stack spacing={2} direction="row">
              <TextField
                label="Comment"
                multiline
                placeholder="Placeholder"
                value={text}
                rows={4}
                onChange={handleChange}
              />
              <Button onClick={() => setMsg(text)}>Set Msg</Button>
            </Stack>
          </Box>
          <Input type="file" onChange={setImgMsg} />
          {useMsgs().map((msg, index) => (
            <Msg key={msg?.id + index.toString()} msg={msg}></Msg>
          ))}
        </Grid>
      </CustomDrawer>
    </div>
  );
};

export default Home;
