import type { NextPage } from "next";
import Head from "next/head";
import React, { useState, useEffect, useRef } from "react";
import { Global, css } from "@emotion/react";
import { atom, useRecoilValue, useSetRecoilState } from "recoil";
import { cssBackgroundState } from "../recoil/States";
import { chatRadioBtnIdState } from "../recoil/States";
import posts from "../.contents/posts.json";
import { CustomPostList } from "../components/PostList";
import { PostItem } from "../types";
import {
  SwipeableTemporaryDrawer,
  CustomDrawer,
} from "../components/GlobalParts";
import { useGetWindowSize } from "../utils/get-window-size";

export const UseReaderContent: React.FC = () => {
  return (
    <>
      <CustomPostList items={posts as PostItem[]} />
    </>
  );
};

const Page: NextPage = () => {
  const { height, width } = useGetWindowSize();
  const cssText = useRecoilValue(cssBackgroundState);
  return (
    <>
      <Global
        styles={css`
          body {
            ${cssText}
          }
        `}
      />
      <Head>
        <title>Hamu House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {width <= 599 && (
        <SwipeableTemporaryDrawer>
          <UseReaderContent></UseReaderContent>
        </SwipeableTemporaryDrawer>
      )}

      {599 < width && (
        <CustomDrawer>
          <UseReaderContent></UseReaderContent>
        </CustomDrawer>
      )}
    </>
  );
};

export default Page;
