import { NextPage } from "next";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import { Stack, Button } from "@mui/material";
import React, { useState, useEffect, useContext, useRef } from "react";
import Grid from "@mui/material/Grid";
import { Input } from "@mui/material";
import Head from "next/head";
import Header from "../components/Header";
import { Global, css } from "@emotion/react";
import {
  GetCssMsg,
  GetCssImg,
  useCssMsgs,
  setCssMsg,
  SetCssTextToAtomBtn,
} from "../components/firebase-theme";
import { atom, useRecoilValue, useSetRecoilState } from "recoil";
import { cssTextState, cssMsgState } from "../recoil/cssMsgStates";

const Page: NextPage = () => {
  /**
██████╗ ███████╗████████╗██╗   ██╗██████╗ ███╗   ██╗
██╔══██╗██╔════╝╚══██╔══╝██║   ██║██╔══██╗████╗  ██║
██████╔╝█████╗     ██║   ██║   ██║██████╔╝██╔██╗ ██║
██╔══██╗██╔══╝     ██║   ██║   ██║██╔══██╗██║╚██╗██║
██║  ██║███████╗   ██║   ╚██████╔╝██║  ██║██║ ╚████║
╚═╝  ╚═╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝
                                                    
 */

  // const setMsgState = useSetRecoilState(cssMsgState);
  const setCssTextState = useSetRecoilState(cssTextState);
  // const msgState = useRecoilValue(cssMsgState);
  const cssText = useRecoilValue(cssTextState);
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    // setMsgState(event.target.value);
    setCssTextState(event.target.value);
  };

  return (
    <>
      <Global
        styles={css`
          body {
            ${cssText}
          }
        `}
      />
      <Head>
        <title>Hamu House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Hamu House"></Header>
      <h1>Theme</h1>
      <Grid direction="row" justifyContent="center" container>
        {/* ███████╗██╗  ██╗███████╗███████╗████████╗
            ██╔════╝██║  ██║██╔════╝██╔════╝╚══██╔══╝
            ███████╗███████║█████╗  █████╗     ██║   
            ╚════██║██╔══██║██╔══╝  ██╔══╝     ██║   
            ███████║██║  ██║███████╗███████╗   ██║   
            ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝   
 */}
        <Grid
          item
          alignItems="center"
          justifyContent="center"
          style={{ minHeight: "100vh" }}
        >
          <h2>Sheet</h2>
          <Stack spacing={2} direction="row">
            <TextField
              multiline
              value={cssText}
              rows={4}
              onChange={handleChange}
            />
            <Button onClick={() => setCssMsg(cssText)}>Set Msg</Button>
          </Stack>
          {useCssMsgs("cssMsgs").map((msg, index) => (
            <div key={index.toString() + "div"}>
              <GetCssMsg
                // TODO msg?.id.toString() cannot delete
                key={msg?.id.toString() + index.toString() + "msg"}
                msg={msg}
              ></GetCssMsg>
              <SetCssTextToAtomBtn
                key={msg?.id.toString() + index.toString() + "css"}
                msg={msg}
              />
            </div>
          ))}
        </Grid>

        {/* ██╗███╗   ███╗ █████╗  ██████╗ ███████╗
            ██║████╗ ████║██╔══██╗██╔════╝ ██╔════╝
            ██║██╔████╔██║███████║██║  ███╗█████╗  
            ██║██║╚██╔╝██║██╔══██║██║   ██║██╔══╝  
            ██║██║ ╚═╝ ██║██║  ██║╚██████╔╝███████╗
            ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
                                        */}
        <Grid item>
          <h2>Image for CSS</h2>
          {useCssMsgs("cssImgMsgs").map((msg, index) => (
            <div key={index.toString() + "div"}>
              <GetCssImg
                // TODO msg?.id.toString() cannot delete
                key={msg?.id.toString() + index.toString() + "msg"}
                msg={msg}
              ></GetCssImg>
            </div>
          ))}
        </Grid>
      </Grid>
    </>
  );
};

export default Page;
